package pkginterface;

import control.BusDetailsControl;
import domain.BusDetailsDomain;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javafx.scene.input.KeyCode.S;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Student
 */
public class BusDetails extends javax.swing.JFrame {

    /**
     * Creates new form BusDetails
     */
    BusDetailsControl bdControl = new BusDetailsControl();

    public BusDetails() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BusID = new javax.swing.JLabel();
        BusIDTF = new javax.swing.JTextField();
        SearchBTN = new javax.swing.JButton();
        BusPlateNum = new javax.swing.JLabel();
        BusColour = new javax.swing.JLabel();
        BusStatus = new javax.swing.JLabel();
        BusType = new javax.swing.JLabel();
        BusTypeCB = new javax.swing.JComboBox();
        TotalSeat = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AddBTN = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        BusStatusCB = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescriptionTA = new javax.swing.JTextArea();
        UpdateBTN = new javax.swing.JButton();
        ViewAllBTN = new javax.swing.JButton();
        BackBTN = new javax.swing.JButton();
        BusPlateNumTF = new org.jdesktop.swingx.JXTextField();
        BusColourTF = new org.jdesktop.swingx.JXTextField();
        TotalSeatTF = new org.jdesktop.swingx.JXTextField();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                BusPlateNumTFCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        Title.setFont(new java.awt.Font("Pristina", 3, 48)); // NOI18N
        Title.setText("               BusMaintenance System");

        BusID.setText("Bus ID");

        BusIDTF.setToolTipText("ONLY FOR SEARCH");
        BusIDTF.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                BusIDTFCaretUpdate(evt);
            }
        });
        BusIDTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusIDTFKeyTyped(evt);
            }
        });

        SearchBTN.setText("Search");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(BusID, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BusIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BusIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBTN))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BusPlateNum.setText("Bus Plate Number*");

        BusColour.setText("Bus Colour*");

        BusStatus.setText("Bus Status*");

        BusType.setText("Bus Type*");

        BusTypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standard", "VIP" }));

        TotalSeat.setText("Total Seat*");

        Description.setText("Description*");

        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("* means compulsory to fill in.");

        AddBTN.setText("Add Bus");
        AddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBusBTN(evt);
            }
        });

        BusStatusCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Available", "Not Available", "Repairing", "Scrap" }));
        BusStatusCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusStatusCBActionPerformed(evt);
            }
        });

        DescriptionTA.setColumns(20);
        DescriptionTA.setRows(5);
        DescriptionTA.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                DescriptionTACaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(DescriptionTA);

        UpdateBTN.setText("Update Bus");
        UpdateBTN.setEnabled(false);
        UpdateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBTNActionPerformed(evt);
            }
        });

        ViewAllBTN.setText("View All Bus");
        ViewAllBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllBTNActionPerformed(evt);
            }
        });

        BackBTN.setText("Back");
        BackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBTNActionPerformed(evt);
            }
        });

        BusPlateNumTF.setPrompt("eg. ABC 1234 / AB 1234 C");
        BusPlateNumTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusPlateNumTFKeyTyped(evt);
            }
        });

        BusColourTF.setPrompt("eg. RED");
        BusColourTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BusColourTFKeyTyped(evt);
            }
        });

        TotalSeatTF.setPrompt(">0 ; <=30");
        TotalSeatTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TotalSeatTFKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BusPlateNum, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BusColour, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TotalSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(BusStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BusStatusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(235, 235, 235)
                                        .addComponent(BusType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BusPlateNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84)
                                        .addComponent(Description))
                                    .addComponent(BusColourTF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TotalSeatTF, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BusTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(ViewAllBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BusPlateNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Description)
                            .addComponent(BusPlateNumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BusColour, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BusColourTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TotalSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalSeatTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BusType)
                                    .addComponent(BusTypeCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BusStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BusStatusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewAllBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBTNActionPerformed
        dispose();
        new MainMenu();
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBTNActionPerformed

    private void AddBusBTN(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBusBTN
        if (BusPlateNumTF.getText().equals("") || BusColourTF.getText().equals("") || TotalSeatTF.getText().equals("") || DescriptionTA.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in all the required field.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            BusDetailsDomain CBPN = bdControl.getRecordWithBPN(BusPlateNumTF.getText());
            if (CBPN != null) {
                JOptionPane.showMessageDialog(null, "The Bus Plate Number is already exist.", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                String busPlateNumRE1 = "[A-Z]{1,3}+ +[0-9]{1,4}+ +[A-Z]{0,1}";
                String busPlateNumRE2 = "[A-Z]{1,3}+ +[0-9]{1,4}";
                String busColourRE = "[a-zA-Z]{3,7}";
                BusDetailsDomain bd = bdControl.getLastRow();
                if (bd != null) {
                    int tempIntBusID = Integer.parseInt(bd.getBusId());
                    tempIntBusID += 1;
                    String tempStrBusID = null;
                    if (tempIntBusID <= 9) {
                        tempStrBusID = "0000" + tempIntBusID;
                    } else if (tempIntBusID <= 99) {
                        tempStrBusID = "000" + tempIntBusID;
                    } else if (tempIntBusID <= 999) {
                        tempStrBusID = "00" + tempIntBusID;
                    } else if (tempIntBusID <= 9999) {
                        tempStrBusID = "0" + tempIntBusID;
                    } else if (tempIntBusID <= 99999) {
                        tempStrBusID = "" + tempIntBusID;
                    }

                    try {
                        if (BusPlateNumTF.getText().matches(busPlateNumRE1) || BusPlateNumTF.getText().matches(busPlateNumRE2)) {
                            if (BusColourTF.getText().matches(busColourRE) && Integer.parseInt(TotalSeatTF.getText()) < 31 && Integer.parseInt(TotalSeatTF.getText()) > 0 && !DescriptionTA.getText().equals("")) {
                                bd = new BusDetailsDomain(tempStrBusID, BusPlateNumTF.getText(), BusColourTF.getText(), (String) BusStatusCB.getSelectedItem(), Integer.parseInt(TotalSeatTF.getText()), DescriptionTA.getText(), (String) BusTypeCB.getSelectedItem());
                                bdControl.addRecord(bd);
                                JOptionPane.showMessageDialog(null, "The New Bus Details is added!\n");
                                BusPlateNumTF.setText("");
                                BusColourTF.setText("");
                                TotalSeatTF.setText("");
                                BusStatusCB.setSelectedIndex(0);
                                DescriptionTA.setText("");
                                BusTypeCB.setSelectedIndex(0);
                            } else {
                                JOptionPane.showMessageDialog(null, "Invalid Input\nBus Plate Number : ABC 1234 / AB 1234 C.\n"
                                        + "BusColour      : Only Character.\n"
                                        + "TotalSeat      : >0;<= 30.\n"
                                        + "Description    : Cannot be blank."
                                        + "*UpperCase Character for Bus Plate Number.*", "ERROR", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid Input\nBus Plate Number : ABC 1234 / AB 1234 C.\n"
                                    + "BusColour      : Only Character.\n"
                                    + "TotalSeat      : >0;<= 30.\n"
                                    + "Description    : Cannot be blank."
                                    + "*UpperCase Character for Bus Plate Number.*", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Invalid Input\nBus Plate Number : ABC 1234 / AB 1234 C.\n"
                                + "BusColour      : Only Character.\n"
                                + "TotalSeat      : >0;<= 30.\n"
                                + "Description    : Cannot be blank."
                                + "*UpperCase Character for Bus Plate Number.*", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }

                }
                if (bd == null) {
                    String busID = "00001";

                    try {
                        if (BusPlateNumTF.getText().matches(busPlateNumRE1) || BusPlateNumTF.getText().matches(busPlateNumRE2)) {
                            if (BusColourTF.getText().matches(busColourRE) && Integer.parseInt(TotalSeatTF.getText()) < 31 && Integer.parseInt(TotalSeatTF.getText()) > 0 && !DescriptionTA.getText().equals("")) {
                                bd = new BusDetailsDomain(busID, BusPlateNumTF.getText(), BusColourTF.getText(), (String) BusStatusCB.getSelectedItem(), Integer.parseInt(TotalSeatTF.getText()), DescriptionTA.getText(), (String) BusTypeCB.getSelectedItem());
                                bdControl.addRecord(bd);
                                JOptionPane.showMessageDialog(null, "The New Bus Details is added!\n");
                                BusPlateNumTF.setText("");
                                BusColourTF.setText("");
                                TotalSeatTF.setText("");
                                BusStatusCB.setSelectedIndex(0);
                                DescriptionTA.setText("");
                                BusTypeCB.setSelectedIndex(0);
                            } else {
                                JOptionPane.showMessageDialog(null, "Invalid Input\nBus Plate Number : ABC 1234 / AB 1234 C.\n"
                                        + "BusColour      : Only Character.\n"
                                        + "TotalSeat      : >0;<= 30.\n"
                                        + "Description    : Cannot be blank."
                                        + "*UpperCase Character for Bus Plate Number.*", "ERROR", JOptionPane.ERROR_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid Input\nBus Plate Number : ABC 1234 / AB 1234 C.\n"
                                    + "BusColour      : Only Character.\n"
                                    + "TotalSeat      : >0;<= 30.\n"
                                    + "Description    : Cannot be blank."
                                    + "*UpperCase Character for Bus Plate Number.*", "ERROR", JOptionPane.ERROR_MESSAGE);
                        }
                    } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(null, "Invalid Input\nBus Plate Number : ABC 1234 / AB 1234 C.\n"
                                + "BusColour      : Only Character.\n"
                                + "TotalSeat      : >0;<= 30.\n"
                                + "Description    : Cannot be blank."
                                + "*UpperCase Character for Bus Plate Number.*", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }


    }//GEN-LAST:event_AddBusBTN


    private void BusStatusCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusStatusCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusStatusCBActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        if (BusIDTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please insert Bus ID to search.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            BusDetailsDomain bd = bdControl.selectRecord(BusIDTF.getText());
            if (bd == null) {
                JOptionPane.showMessageDialog(null, "Record not found.", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                BusPlateNumTF.setText(bd.getBusPlateNum());
                BusColourTF.setText(bd.getBusColour());
                TotalSeatTF.setText("" + bd.getTotalSeat());
                BusStatusCB.setSelectedItem(bd.getBusStatus());
                DescriptionTA.setText(bd.getDescription());
                BusTypeCB.setSelectedItem(bd.getBusType());
            }
        }
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void BusIDTFCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_BusIDTFCaretUpdate
        if (!BusIDTF.getText().equals("")) {
            AddBTN.setEnabled(false);
            BusPlateNumTF.setEditable(false);
        } else {
            AddBTN.setEnabled(true);
            BusPlateNumTF.setEditable(true);
            UpdateBTN.setEnabled(false);

            //Clear Input
            BusPlateNumTF.setText("");
            BusColourTF.setText("");
            TotalSeatTF.setText("");
            BusStatusCB.setSelectedIndex(0);
            DescriptionTA.setText("");
            BusTypeCB.setSelectedIndex(0);
        }
    }//GEN-LAST:event_BusIDTFCaretUpdate

    private void UpdateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBTNActionPerformed
        String busPlateNumRE1 = "[A-Z]{1,3}+ +[0-9]{1,4}+ +[A-Z]{0,1}";
        String busPlateNumRE2 = "[A-Z]{1,3}+ +[0-9]{1,4}";
        String busColourRE = "[a-zA-Z]{3,7}";

        try {
            if (BusPlateNumTF.getText().matches(busPlateNumRE1) || BusPlateNumTF.getText().matches(busPlateNumRE2)) {
                if (BusColourTF.getText().matches(busColourRE) && Integer.parseInt(TotalSeatTF.getText()) < 31 && !DescriptionTA.getText().equals("")) {
                    BusDetailsDomain db = new BusDetailsDomain(BusIDTF.getText(), BusPlateNumTF.getText(), BusColourTF.getText(), (String) BusStatusCB.getSelectedItem(), Integer.parseInt(TotalSeatTF.getText()), DescriptionTA.getText(), (String) BusTypeCB.getSelectedItem());
                    bdControl.updateRecord(db);
                    JOptionPane.showMessageDialog(null, "The Bus Details is updated!");
                    BusIDTF.setText("");
                    BusPlateNumTF.setText("");
                    BusColourTF.setText("");
                    TotalSeatTF.setText("");
                    BusStatusCB.setSelectedIndex(0);
                    DescriptionTA.setText("");
                    BusTypeCB.setSelectedIndex(0);
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Input\nBus Plate Number : ABC 1234 / AB 1234 C.\n"
                            + "BusColour      : Only Character.\n"
                            + "TotalSeat      : >0;<= 30.\n"
                            + "Description    : Cannot be blank."
                            + "*UpperCase Character for Bus Plate Number.*", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Input\nBus Plate Number : ABC 1234 / AB 1234 C.\n"
                        + "BusColour      : Only Character.\n"
                        + "TotalSeat      : >0;<= 30.\n"
                        + "Description    : Cannot be blank."
                        + "*UpperCase Character for Bus Plate Number.*", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid Input\nBus Plate Number : ABC 1234 / AB 1234 C.\n"
                    + "BusColour      : Only Character.\n"
                    + "TotalSeat      : >0;<= 30.\n"
                    + "Description    : Cannot be blank."
                    + "*UpperCase Character for Bus Plate Number.*", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_UpdateBTNActionPerformed

    private void ViewAllBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllBTNActionPerformed
        new ViewAllBus();        // TODO add your handling code here:
    }//GEN-LAST:event_ViewAllBTNActionPerformed

    private void BusPlateNumTFCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_BusPlateNumTFCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BusPlateNumTFCaretPositionChanged

    private void DescriptionTACaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_DescriptionTACaretUpdate
        if (!BusIDTF.getText().equals("") && !BusPlateNumTF.getText().equals("") && !BusColourTF.getText().equals("") && !TotalSeatTF.getText().equals("") && !DescriptionTA.getText().equals("")) {
            UpdateBTN.setEnabled(true);
        } else if (BusIDTF.getText().equals("") || BusPlateNumTF.getText().equals("") || BusColourTF.getText().equals("") || TotalSeatTF.getText().equals("") || DescriptionTA.getText().equals("")) {
            UpdateBTN.setEnabled(false);
        }
    }//GEN-LAST:event_DescriptionTACaretUpdate

    private void TotalSeatTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TotalSeatTFKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) || TotalSeatTF.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_TotalSeatTFKeyTyped

    private void BusPlateNumTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusPlateNumTFKeyTyped
        if (BusPlateNumTF.getText().length() >= 10) {
            evt.consume();
        }      // TODO add your handling code here:
    }//GEN-LAST:event_BusPlateNumTFKeyTyped

    private void BusIDTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusIDTFKeyTyped
        if (BusIDTF.getText().length() >= 5) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BusIDTFKeyTyped

    private void BusColourTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BusColourTFKeyTyped
        if (BusColourTF.getText().length() >= 7) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BusColourTFKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusDetails().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBTN;
    private javax.swing.JButton BackBTN;
    private javax.swing.JLabel BusColour;
    private org.jdesktop.swingx.JXTextField BusColourTF;
    private javax.swing.JLabel BusID;
    javax.swing.JTextField BusIDTF;
    private javax.swing.JLabel BusPlateNum;
    private org.jdesktop.swingx.JXTextField BusPlateNumTF;
    private javax.swing.JLabel BusStatus;
    javax.swing.JComboBox BusStatusCB;
    private javax.swing.JLabel BusType;
    javax.swing.JComboBox BusTypeCB;
    private javax.swing.JLabel Description;
    javax.swing.JTextArea DescriptionTA;
    private javax.swing.JButton SearchBTN;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TotalSeat;
    private org.jdesktop.swingx.JXTextField TotalSeatTF;
    private javax.swing.JButton UpdateBTN;
    private javax.swing.JButton ViewAllBTN;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
