/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import static com.sun.javafx.tk.Toolkit.getToolkit;
import control.BusDetailsControl;
import control.BusScheduleControl;
import control.CustCardDetailsControl;
import control.CustTypeControl;
import control.PaymentDetailsControl;
import control.TransactionControl;
import domain.BusDetailsDomain;
import domain.BusScheduleDomain;
import domain.CustTypeDomain;
import domain.CustcardDetails;
import domain.PaymentDetails;
import domain.TransactionDetails;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author waiho
 */
public class PayByCard extends javax.swing.JFrame {

    TransactionControl tControl = new TransactionControl();
    BusScheduleControl bsControl = new BusScheduleControl();
    CustTypeControl ctControl = new CustTypeControl();
    CustCardDetailsControl cdControl = new CustCardDetailsControl();
    PaymentDetailsControl pControl = new PaymentDetailsControl();
    double total = 0;
    String tempD = null;
    String tempI = null;

    /**
     * Creates new form CardPay
     */
    public PayByCard() {
        initComponents();
        setLocationRelativeTo(null);
        PaymentDetails pd = pControl.getLastRow();
        if (pd != null) {
            PaymentDetails paymentDetails = pControl.getRecord(pd.getPaycountId());
            total = paymentDetails.getTotalAmount();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtf1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Pristina", 3, 48)); // NOI18N
        jLabel1.setText("Card Pay");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Card Number   :");

        jtf1.setColumns(4);
        jtf1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf1ActionPerformed(evt);
            }
        });
        jtf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf1KeyTyped(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visa_mastercard_2.gif"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Expiration Date :");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField5.setText("mm");
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField6.setText("yyyy");
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("CVV Code :");

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Name On Card :");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        jTextField5.setText("");
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
        jTextField6.setText("");
    }//GEN-LAST:event_jTextField6FocusGained

    private void jtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtf1ActionPerformed

    private void jtf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) || jtf1.getText().length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_jtf1KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) || jTextField4.getText().length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) || jTextField3.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) || jTextField2.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) || jTextField5.getText().length() > 1) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) || jTextField6.getText().length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE) || jTextField7.getText().length() > 2) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int year = Calendar.getInstance().get(Calendar.YEAR);
        String stryear = jTextField6.getText();
        int keyInYear = Integer.parseInt(stryear);
        int Month = Integer.parseInt(jTextField5.getText());

        if (jtf1.getText().equals("") || jTextField4.getText().equals("") || jTextField3.getText().equals("") || jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Fill Up All the Card Numbers");
            jtf1.setText("");
            jTextField4.setText("");
            jTextField3.setText("");
            jTextField2.setText("");

        } else if (Month > 12 || jTextField5.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid Month Detected! \nPlease Try Again!");
            jTextField5.setText("");
        } else if (keyInYear < year || jTextField6.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid Year Detected! \nPlease Try Again!");
            jTextField6.setText("");
        } else if (jTextField8.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You Should Key In Card Holder Name!");
        } else {
            ResultSet trs = null;
            trs = tControl.getRecordWithTranstStatus("Pending");
            try {
                while (trs.next()) {

                    TransactionDetails transID = tControl.getRecord(trs.getString(1));
                    String id = transID.getTranstId();
                    String status = "Paid";
                    TransactionDetails setPaid = new TransactionDetails(status, id);
                    tControl.setStatus(setPaid);

                }
            } catch (SQLException ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NumberFormatException e) {
            }

            String cardNum = jtf1.getText() + jTextField4.getText() + jTextField3.getText() + jTextField2.getText();
            String cardMonth = jTextField5.getText();
            String cardYear = jTextField6.getText();
            String cvv = jTextField7.getText();
            String cardHolder = jTextField8.getText();
            String tempStrCustCardID = null;
            CustcardDetails cd = cdControl.getLastRow();
            if (cd != null) {
                int tempIntCustCardID = Integer.parseInt(cd.getCustcardId());
                tempIntCustCardID += 1;

                if (tempIntCustCardID <= 9) {
                    tempStrCustCardID = "0000" + tempIntCustCardID;
                } else if (tempIntCustCardID <= 99) {
                    tempStrCustCardID = "000" + tempIntCustCardID;
                } else if (tempIntCustCardID <= 999) {
                    tempStrCustCardID = "00" + tempIntCustCardID;
                } else if (tempIntCustCardID <= 9999) {
                    tempStrCustCardID = "0" + tempIntCustCardID;
                } else if (tempIntCustCardID <= 99999) {
                    tempStrCustCardID = "" + tempIntCustCardID;
                }
                cd = new CustcardDetails(tempStrCustCardID, cardNum, cardMonth, cardYear, cvv, cardHolder);
                cdControl.addRecord(cd);
            } else {
                tempStrCustCardID = "00001";
                cd = new CustcardDetails(tempStrCustCardID, cardNum, cardMonth, cardYear, cvv, cardHolder);
                cdControl.addRecord(cd);
            }

            int confirmDialog = JOptionPane.showConfirmDialog(rootPane, "Payment Completed!\nDo you want to generate receipt?", null, YES_NO_OPTION);

            //This part is to generate ticket
            Document document = new Document();
            Document document1 = new Document();
            BusDetailsControl bdControl = new BusDetailsControl();
            BusScheduleControl bsControl = new BusScheduleControl();
            CustTypeControl ctControl = new CustTypeControl();
            ResultSet rs = Payment.getForTandR();
            PdfWriter writer = null;
            try {
                writer = PdfWriter.getInstance(document, new FileOutputStream("../" + Payment.getPaymentID() + ".pdf"));
                document.open();
                while (rs.next()) {
                    BusScheduleDomain bs = bsControl.getRecord(rs.getString(2));
                    BusDetailsDomain bd = bdControl.getRecord(bs.getBusId().getBusId());
                    CustTypeDomain ct = ctControl.getRecord(rs.getString(3));
                    tempD = bs.getDepartLocation();
                    tempI = bs.getArriveLocation();
                    document.add(new Paragraph("TICKET"));
                    document.add(new Paragraph("Depart Location         : " + bs.getDepartLocation()));
                    document.add(new Paragraph("Arrive Location          : " + bs.getArriveLocation()));
                    document.add(new Paragraph("Depart Date              : " + bs.getScheduleDate()));
                    document.add(new Paragraph("Depart Time              : " + bs.getScheduleTime()));
                    document.add(new Paragraph("Customer Type         : " + ct.getCustType()));
                    document.add(new Paragraph("Bus Plate Number    : " + bd.getBusPlateNum()));
                    document.add(new Paragraph("Bus Type                  : " + bd.getBusType()));
                    document.add(new Paragraph("Price                         : " + bs.getPrice() * ct.getDiscountRate()));
                    document.add(new Paragraph(" "
                            + " "));

                }
            } catch (DocumentException e) {
                e.printStackTrace();
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (SQLException ex) {
                Logger.getLogger(PayByCash.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (confirmDialog == JOptionPane.YES_OPTION) {
                PdfWriter writer1 = null;
                Date today = new Date();
                SimpleDateFormat dateF = new SimpleDateFormat("d-M-yyyy");
                SimpleDateFormat timeF = new SimpleDateFormat("HH:mm:ss");
                try {
                    writer1 = PdfWriter.getInstance(document1, new FileOutputStream("../" + Payment.getPaymentID() + " Receipt.pdf"));
                    document1.open();
                    document1.add(new Paragraph("                        SERI MEJU BUS Malaysia Sdn. Bhd."));
                    document1.add(new Paragraph("                        L3-11, JLN LINGKARAN TENGAG LI,"));
                    document1.add(new Paragraph("                               BANDAR TASIK SELATAN,"));
                    document1.add(new Paragraph("                                57100 KUALA LUMPUR,"));
                    document1.add(new Paragraph("                 WILAYAH PERSEKUTUAN KUALA LUMPUR,"));
                    document1.add(new Paragraph("                                           MALAYSIA"));
                    document1.add(new Paragraph(" "));
                    document1.add(new Paragraph("RECEIPT"));
                    document1.add(new Paragraph("---------------------------------------------------------------------------------------------"));
                    document1.add(new Paragraph("Staff ID : " + new StaffMaintenance().getLoginUser()));
                    document1.add(new Paragraph("Date : " + dateF.format(today)));
                    document1.add(new Paragraph("Time : " + timeF.format(today)));
                    document1.add(new Paragraph("From : " + tempD + ">>>>>>>>>>>>>>>>>>" + "To : " + tempI));
                    document1.add(new Paragraph("Total : " + total));
                    document1.add(new Paragraph("Payment Type : Cash "));
                    document1.add(new Paragraph("---------------------------------------------------------------------------------------------"));
                    document1.add(new Paragraph("Contact us : "));
                    document1.add(new Paragraph("(Tel)1300-88-1111          (Email)serimejubusservice@gmail.com"));
                    document1.close();
                    JOptionPane.showMessageDialog(null, "The Ticket(s) and Receipt have been stored to the Desktop of this PC.");
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(PayByCash.class.getName()).log(Level.SEVERE, null, ex);
                } catch (DocumentException ex) {
                    Logger.getLogger(PayByCash.class.getName()).log(Level.SEVERE, null, ex);
                }

            }else{
                JOptionPane.showMessageDialog(null, "The Ticket(s) have been stored to the Desktop of this PC.");
            }

            document.close();
            writer.close();

            new MainMenu();
            dispose();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayByCard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayByCard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayByCard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayByCard.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayByCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jtf1;
    // End of variables declaration//GEN-END:variables
}
