/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

import control.BusDetailsControl;
import domain.BusDetailsDomain;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class ViewAllBus extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllBus
     */
    BusDetailsControl bdControl = new BusDetailsControl();
    ResultSet rs;

    public ViewAllBus() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        rs = bdControl.retrieveRecord();
        int row = 0;
        try {
            while (rs.next()) {
                for (int col = 0; col < 7; col++) {
                    jTable1.setValueAt(rs.getString(col + 1), row, col);
                }
                row++;

            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewAllBus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        BusIDRB = new javax.swing.JRadioButton();
        BusPlateNumRB = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        busStatusRB = new javax.swing.JRadioButton();
        SearchTF = new org.jdesktop.swingx.JXTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Title.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        Title.setText("View All Bus Details");

        BusIDRB.setText("Bus ID");
        BusIDRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusIDRBActionPerformed(evt);
            }
        });

        BusPlateNumRB.setText("Bus Plate Number");
        BusPlateNumRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusPlateNumRBActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Bus ID", "Bus Plate Num", "Bus Colour", "Bus Status", "Total Seat", "Description", "Bus Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        busStatusRB.setText("Bus Status");
        busStatusRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busStatusRBActionPerformed(evt);
            }
        });

        SearchTF.setPrompt("Status : Available / Repairing / Not Available / Scrap");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BusIDRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(BusPlateNumRB)
                                        .addGap(27, 27, 27)
                                        .addComponent(busStatusRB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton1)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BusIDRB)
                    .addComponent(BusPlateNumRB)
                    .addComponent(busStatusRB))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(SearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BusIDRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusIDRBActionPerformed
        BusPlateNumRB.setSelected(false);
        busStatusRB.setSelected(false);
    }//GEN-LAST:event_BusIDRBActionPerformed

    private void BusPlateNumRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusPlateNumRBActionPerformed
        BusIDRB.setSelected(false);
        busStatusRB.setSelected(false);
    }//GEN-LAST:event_BusPlateNumRBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (SearchTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in data to search.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            if (BusIDRB.isSelected()) {
                BusDetailsDomain bd = bdControl.getRecord(SearchTF.getText());
                //Clear jTable
                for (int row = 0; row < jTable1.getRowCount(); row++) {
                    for (int col = 0; col < 7; col++) {
                        jTable1.setValueAt("", row, col);
                    }
                }
                if (bd == null) {
                    JOptionPane.showMessageDialog(null, "Record not found.", "ERROR", JOptionPane.ERROR_MESSAGE);

                } else {
                    //Insert date into jTable
                    jTable1.setValueAt(bd.getBusId(), 0, 0);
                    jTable1.setValueAt(bd.getBusPlateNum(), 0, 1);
                    jTable1.setValueAt(bd.getBusColour(), 0, 2);
                    jTable1.setValueAt(bd.getBusStatus(), 0, 3);
                    jTable1.setValueAt(bd.getTotalSeat(), 0, 4);
                    jTable1.setValueAt(bd.getDescription(), 0, 5);
                    jTable1.setValueAt(bd.getBusType(), 0, 6);
                }

            } else if (BusPlateNumRB.isSelected()) {
                BusDetailsDomain bd = bdControl.getRecordWithBPN(SearchTF.getText());
                //Clear jTable
                for (int row = 0; row < jTable1.getRowCount(); row++) {
                    for (int col = 0; col < 7; col++) {
                        jTable1.setValueAt("", row, col);
                    }
                }
                if (bd == null) {
                    JOptionPane.showMessageDialog(null, "Record not found.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    SearchTF.setText("");

                } else {
                    //Insert date into jTable
                    jTable1.setValueAt(bd.getBusId(), 0, 0);
                    jTable1.setValueAt(bd.getBusPlateNum(), 0, 1);
                    jTable1.setValueAt(bd.getBusColour(), 0, 2);
                    jTable1.setValueAt(bd.getBusStatus(), 0, 3);
                    jTable1.setValueAt(bd.getTotalSeat(), 0, 4);
                    jTable1.setValueAt(bd.getDescription(), 0, 5);
                    jTable1.setValueAt(bd.getBusType(), 0, 6);
                }
            } else if (busStatusRB.isSelected()) {
                ResultSet rs = bdControl.retrieveRecord();
                //Clear jTable
                for (int row = 0; row < jTable1.getRowCount(); row++) {
                    for (int col = 0; col < 7; col++) {
                        jTable1.setValueAt("", row, col);
                    }
                }
                try {
                    //Insert date into jTable
                    int row=0;
                    while (rs.next()) {
                        int check =0;
                        for (int col = 0; col < 7; col++) {
                            if (rs.getString(4).equals(SearchTF.getText())) {
                                jTable1.setValueAt(rs.getString(col + 1), row, col);
                                check =1;
                            }
                        }
                        if(check==1){
                            row++;
                        }
                    }
                    if(jTable1.getValueAt(0, 0).equals("")){
                        JOptionPane.showMessageDialog(null, "Record not found.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(ViewAllBus.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please select 1 option to search.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void busStatusRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busStatusRBActionPerformed
        BusPlateNumRB.setSelected(false);
        BusIDRB.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_busStatusRBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BusIDRB;
    private javax.swing.JRadioButton BusPlateNumRB;
    private org.jdesktop.swingx.JXTextField SearchTF;
    private javax.swing.JLabel Title;
    private javax.swing.JRadioButton busStatusRB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
