/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkginterface;

import javax.swing.JOptionPane;
import control.BusScheduleControl;
import domain.BusScheduleDomain;
import control.BusDetailsControl;
import domain.BusDetailsDomain;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Student
 */
public class ViewAllSche extends javax.swing.JFrame {

    /**
     * Creates new form ViewAllSche
     */
    //Create Domain and Control
    BusScheduleControl bsControl = new BusScheduleControl();
    BusScheduleDomain bs = null;
    BusDetailsControl bdControl = new BusDetailsControl();
    BusDetailsDomain bd = null;

    public ViewAllSche() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);

        //Retrieve data from Bus Schedule Database
        ResultSet rs = bsControl.retrieveRecord();
        int row = 0;
        try {
            while (rs.next()) {
                bd = bdControl.getRecord(rs.getString(8));
                jTable1.setValueAt(rs.getString(1), row, 0);
                jTable1.setValueAt(rs.getString(3), row, 1);
                jTable1.setValueAt(rs.getString(2), row, 2);
                jTable1.setValueAt(rs.getString(6), row, 3);
                jTable1.setValueAt(rs.getString(7), row, 4);
                jTable1.setValueAt(bd.getBusType(), row, 5);
                jTable1.setValueAt(rs.getString(8), row, 6);
                row++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ViewAllSche.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScheduleIDRB = new javax.swing.JRadioButton();
        ScheduleDateRB = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Title = new javax.swing.JLabel();
        SearchBTN = new javax.swing.JButton();
        SearchTF = new org.jdesktop.swingx.JXTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ScheduleIDRB.setText("Schedule_ID");
        ScheduleIDRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleIDRBActionPerformed(evt);
            }
        });

        ScheduleDateRB.setText("Schedule_Date");
        ScheduleDateRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleDateRBActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Schedule_ID", "Schedule_Time", "Schedule_Date", "From_Location", "To_Location", "Type", "Bus_ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Title.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        Title.setText("View All Bus Schedule");

        SearchBTN.setText("Search");
        SearchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBTNActionPerformed(evt);
            }
        });

        SearchTF.setPrompt("Date format : d-M-yyyy");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ScheduleIDRB)
                                        .addGap(18, 18, 18)
                                        .addComponent(ScheduleDateRB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(SearchBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 293, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ScheduleIDRB)
                    .addComponent(ScheduleDateRB))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBTN)
                    .addComponent(SearchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ScheduleIDRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleIDRBActionPerformed
        ScheduleDateRB.setSelected(false);
    }//GEN-LAST:event_ScheduleIDRBActionPerformed

    private void ScheduleDateRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleDateRBActionPerformed
        ScheduleIDRB.setSelected(false);
    }//GEN-LAST:event_ScheduleDateRBActionPerformed

    private void SearchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBTNActionPerformed
        if (SearchTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill in data to search.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (ScheduleIDRB.isSelected() == false && ScheduleDateRB.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Please select 1 option to search.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (ScheduleIDRB.isSelected()) {
            //Get record from BusSchedule Database
            bs = bsControl.getRecord(SearchTF.getText());

            //Clear jTable1
            for (int row = 0; row < jTable1.getRowCount(); row++) {
                for (int col = 0; col < 7; col++) {
                    jTable1.setValueAt("", row, col);
                }
            }
            if (bs != null) {
                //Get Bus type
                bd = bdControl.getRecord(bs.getBusId().getBusId());
                
                jTable1.setValueAt(bs.getScheduleId(), 0, 0);
                jTable1.setValueAt(bs.getScheduleTime(), 0, 1);
                jTable1.setValueAt(bs.getScheduleDate(), 0, 2);
                jTable1.setValueAt(bs.getDepartLocation(), 0, 3);
                jTable1.setValueAt(bs.getArriveLocation(), 0, 4);
                jTable1.setValueAt(bd.getBusType(), 0, 5);
                jTable1.setValueAt(bs.getBusId().getBusId(), 0, 6);
            } else {
                JOptionPane.showMessageDialog(null, "Record not found.", "ERROR", JOptionPane.ERROR_MESSAGE);
                SearchTF.setText("");
            }
        } else {
            //Retrieve all Data from Bus Schedule Database
            ResultSet rs = bsControl.retrieveRecord();

            //Clear jTable1
            for (int row = 0; row < jTable1.getRowCount(); row++) {
                for (int col = 0; col < 7; col++) {
                    jTable1.setValueAt("", row, col);
                }
            }
            try {
                int row = 0;
                while (rs.next()) {
                    if (rs.getString(2).equals(SearchTF.getText())) {
                        //Get Bus Type
                        bd = bdControl.getRecord(rs.getString(8));
                        jTable1.setValueAt(rs.getString(1), row, 0);
                        jTable1.setValueAt(rs.getString(3), row, 1);
                        jTable1.setValueAt(rs.getString(2), row, 2);
                        jTable1.setValueAt(rs.getString(6), row, 3);
                        jTable1.setValueAt(rs.getString(7), row, 4);
                        jTable1.setValueAt(bd.getBusType(), row, 5);
                        jTable1.setValueAt(rs.getString(8), row, 6);
                        row++;
                    }
                }
                if (row==0) {
                    JOptionPane.showMessageDialog(null, "Record not found.", "ERROR", JOptionPane.ERROR_MESSAGE);
                    SearchTF.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(ViewAllSche.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_SearchBTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllSche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllSche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllSche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllSche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new ViewAllSche().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ScheduleDateRB;
    private javax.swing.JRadioButton ScheduleIDRB;
    private javax.swing.JButton SearchBTN;
    private org.jdesktop.swingx.JXTextField SearchTF;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
